### ISSUE TITLE
Color settings.

### ISSUE THREAD

**Issue by lukasoppermann** [EXSyst/recent-projects#1]
Hey,

I would suggest removing the redefined color variables at the top of the stylesheet and changing the button border color to `@button-background-color-selected`.
Otherwise one gets a very hard to read experience for the button and a way to strong contrast with dark themes.

``` css
    .btn-default,
    .btn-group > .btn-default {
        background-color: #fff;
        color: @text-color;
        border: 1px solid @button-background-color-selected;

        &:hover {
            color: @text-color;
            background-color: #ddd;
        }
    }
```
