### ISSUE TITLE
Suggestion: Set tile bg color independent of theme

### ISSUE THREAD

**Issue by bennyp123** [EXSyst/recent-projects#39]
Specifically, I suggest a toggle in settings for tile background: light or dark.

Best,
B

**Comment by Ener-Getick** [comment]
Why do you want to set it independently of the theme ?

**Comment by Ener-Getick** [comment]
You can edit your stylesheet (``Edit`` \ ``Open your stylesheet``).

An example for a light theme: 
```less
.recent-projects-view {
    .btn-default {
        background-color: #dddddd;
        &:focus, &:hover {
            background-color: #eee;
        }
    }

    .project-meta {
        background-color: rgba(0, 0, 0, 0.5)
    }
}
```
